config/routes.rb
Dashboard2::Application.routes.draw do
  resources :nodes
  resources :node_groups
  resources :node_classes
  root :to => 'nodes#index'

end

app/models/node.rb
class Node < ActiveRecord::Base
  attr_accessible :name
  default_scope order('name ASC')

  has_many :reports
  has_many :node_group_memberships
  has_many :node_groups, :through => :node_group_memberships
  has_many :node_class_memberships
  has_many :node_classes, :through => :node_class_memberships
  has_many :parameters, :as => :parameterable

  def classes
    node_classes
  end

  def groups
    node_groups
  end
end

app/models/node_class.rb
class NodeClass < ActiveRecord::Base
  has_many :node_class_memberships
  has_many :nodes, :through => :node_class_memberships
  has_many :parameters, :as => :parameterable
end

app/models/node_class_membership.rb
class NodeClassMembership < ActiveRecord::Base
  belongs_to :node
  belongs_to :node_class
end

app/models/node_group.rb
class NodeGroup < ActiveRecord::Base
  has_many :node_group_memberships
  has_many :nodes, :through => :node_group_memberships
  has_many :parameters, :as => :parameterable
end

app/models/node_group_membership.rb
class NodeGroupMembership < ActiveRecord::Base
  belongs_to :node
  belongs_to :node_group
end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
  belongs_to :parameterable, :polymorphic => true
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :node
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/node_classes_controller.rb
class NodeClassesController < ApplicationController
  def index
    @node_classes = NodeClass.all
  end

  def show
    @node_class = NodeClass.find(params[:id])
  end
end

app/controllers/node_groups_controller.rb
class NodeGroupsController < ApplicationController
  def index
    @node_groups = NodeGroup.all
  end

  def show
    @node_group = NodeGroup.find(params[:id])
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  def index
    @nodes = Node.all

    respond_to do |wants|
      wants.html {}
      wants.json { render :json => @nodes.to_json }
    end
  end

  def show
    @node = Node.find(params[:id])

    respond_to do |wants|
      wants.html {}
      wants.json { render :json => @node.parameters.to_json }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dashboard2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Dashboard2</a>
    <ul class="nav">
      <li><%= link_to "Nodes", nodes_path %></li>
      <li><%= link_to "Classes", node_classes_path %></li>
      <li><%= link_to "Groups", node_groups_path %></li>
    </ul>
  </div>
</div>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/node_classes/index.html.erb
<h1>Classes</h1>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Nodes</th>
  </tr>
  <% @node_classes.each do |node_class| %>
    <tr>
      <td><%= link_to node_class.name, node_class_path(node_class) %></td>
      <td><%= node_class.nodes.count %></td>
    </tr>
  <% end %>
</table>

app/views/node_classes/show.html.erb
<h1><%= @node_class.name %></h1>
<p>
  <%= link_to "Back", node_classes_path, :class => "btn" %>
</p>
<h2>Nodes</h2>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Status</th>
  </tr>
  <% @node_class.nodes.each do |node| %>
    <tr>
      <td><%= link_to node.name, node_path(node) %></td>
      <td><%= node.status %></td>
    </tr>
  <% end %>
</table>

app/views/node_groups/index.html.erb
<h1>Groups</h1>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Nodes</th>
  </tr>
  <% @node_groups.each do |node_group| %>
    <tr>
      <td><%= link_to node_group.name, node_group_path(node_group) %></td>
      <td><%= node_group.nodes.count %></td>
    </tr>
  <% end %>
</table>

app/views/node_groups/show.html.erb
<h1><%= @node_group.name %></h1>
<p>
  <%= link_to "Back", node_groups_path, :class => "btn" %>
</p>
<h2>Parameters</h2>
<table class="table">
  <tr>
    <th>Key</th>
    <th>Value</th>
  </tr>
  <% @node_group.parameters.each do |parameter| %>
    <tr>
      <td><%= parameter.key %></td>
      <td><%= parameter.value %></td>
    </tr>
  <% end %>
</table>
<h2>Nodes</h2>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Status</th>
  </tr>
  <% @node_group.nodes.each do |node| %>
    <tr>
      <td><%= link_to node.name, node_path(node) %></td>
      <td><%= node.status %></td>
    </tr>
  <% end %>
</table>

app/views/nodes/index.html.erb
<h1>Nodes</h1>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Status</th>
  </tr>
  <% @nodes.each do |node| %>
    <tr>
      <td><%= link_to node.name, node_path(node) %></td>
      <td><%= node.status %></td>
    </tr>
  <% end %>
</table>

app/views/nodes/show.html.erb
<h1><%= @node.name %></h1>
<p>
  <%= link_to "Back", nodes_path, :class => "btn" %>
</p>

<h2>Parameters</h2>
<table class="table">
  <tr>
    <th>Key</th>
    <th>Value</th>
  </tr>
  <% (@node.groups.collect{|v|v} << @node).each do |object| %>
    <% object.parameters.each do |parameter| %>
      <tr>
        <td><%= object.name %></td>
        <td><%= parameter.key %></td>
        <td><%= parameter.value %></td>
      </tr>
    <% end %>
  <% end %>
</table>

<h2>Classes</h2>
<ul>
  <% @node.classes.each do |node_class| %>
    <li><%= link_to node_class.name, node_class_path(node_class) %></li>
  <% end %>
</ul>

<h2>Groups</h2>
<ul>
  <% @node.groups.each do |group| %>
    <li><%= link_to group.name, node_group_path(group) %></li>
  <% end %>
</ul>

<h2>Reports</h2>
<table class="table">
  <tr>
    <th>Time</th>
    <th>Status</th>
  </tr>
  <% @node.reports.each do |report| %>
    <tr>
      <td><%= report.time %></td>
      <td><%= report.status %></td>
    </tr>
  <% end %>
</table>